name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    name: ESLint 检查
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: TypeScript 类型检查
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TypeScript check
        run: npm run check

  e2e-smoke:
    name: E2E 冒烟测试
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Create test env file
        run: |
          mkdir -p api
          cat > api/.env << EOF
          VOLCENGINE_ARK_API_KEY=test_key
          VOLCENGINE_TTS_ACCESS_TOKEN=test_token
          VOLCENGINE_APP_ID=test_app_id
          RUN_MODE=sandbox
          USE_MOCK_SERVICES=true
          EOF
      
      - name: Start development server
        run: npm run dev &
        env:
          CI: true
      
      - name: Wait for server
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:5173/debug/api; do sleep 2; done'
      
      - name: Run smoke tests
        run: npx playwright test tests/e2e/main-workflow.spec.ts
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30